sudo: required
dist: bionic
language: csharp
mono: none
dotnet: 3.1.11
solution: Prompto.sln
script:
  - dotnet build -c Release -f netstandard2.0 ./CSharp-Core/CSharp-Core.csproj 
  - dotnet build -c Release -f netstandard2.0 ./CSharp-Runtime/CSharp-Runtime.csproj 
  - dotnet build -c Release -f netcoreapp3.1 ./CSharp-Tests/CSharp-Tests.csproj 
  - dotnet test -f netcoreapp3.1 ./CSharp-Tests/bin/Release/netcoreapp3.1/CSharp-Tests.dll 