sudo: true
language: csharp
solution: Prompto.sln
install:
  - nuget install NUnit.Runners -Version 3.6.1 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release Prompto.sln
  - mono ./testrunner/NUnit.ConsoleRunner.3.2.0/tools/nunit3-console.exe ./CSharp-Tests/bin/Release/CSharp-Tests.dll